import type {Metadata} from "next";
import "./globals.css";

//components
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
 title: "Sellaris Dashboard",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang="en">
   <body className="flex  bg-[#f4f4f4]">
    <Sidebar />
    {children}
   </body>
  </html>
 );
}
